import { Inter } from "next/font/google";
import "./ui/globals.css";
import Dashboard from "./dashboard/page";
import Providers from "../lib/provider";
// import { persistor, store } from "../lib/store";
// import { PersistGate } from 'redux-persist/integration/react';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CoverQ Core",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script src="http://localhost:8097"></script>
        <body className={inter.className}>
          <Providers>
            {/* <PersistGate loading={null} persistor={persistor}> */}
              {children}
            {/* </PersistGate> */}
          </Providers>
        </body>
      </head>
    </html>
  );
}
