import { Inter } from "next/font/google";
import "./ui/globals.css";
import Dashboard from "./dashboard/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <script src="http://localhost:8097"></script>
        <body className={inter.className}>
          {children}
        </body>
      </head>
    </html>
  );
}
